/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempLoginPackage;

import java.io.BufferedReader;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import partitaOnline.controller.PartitaOnlineController;
import partitaOnline.view.PartitaOnlineGuiView;

/**
 *
 * @author root
 */
public class SalaDiAspetto extends javax.swing.JFrame {

    private PartitaOnlineController controller;
    private String nome;

    /**
     * Creates new form SalaDiAspetto
     */
    public SalaDiAspetto(Socket socketClient, BufferedReader in) {
        try {
            initComponents();
            this.setVisible(true);
            aspettaConnessione(in, socketClient);
        } catch (IOException ex) {
            Logger.getLogger(SalaDiAspetto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void aspettaConnessione(BufferedReader in, Socket socketClient) throws IOException {
        String risposta = in.readLine();
        if (risposta.equals("evento\tIniziaPartita")) {
            controller = new PartitaOnlineController(socketClient, in, nome);
            new PartitaOnlineGuiView(controller);
            this.setVisible(false);
        }else if(risposta.startsWith("setta\tNome")){
            String dati[]=risposta.split("\t");
            nome=dati[2];
            aspettaConnessione(in, socketClient);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 700));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dominio/immagini/paperaSorridente.jpg"))); // NOI18N
        jLabel1.setText("LA PARTITA SI STA CARICANDO");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 700));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
